[package]
name = "turnstile"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
anyhow = "*"
sodiumoxide = "0.2.7"
shellexpand = "*"